### ISSUE TITLE
Using quill-render for html mails

### ISSUE THREAD

**Issue by LarsBuur** [casetext/quill-render#3]
I really like the simplicity of your module and the fact that it uses cheerio. I cant seem to get rendering of span tags with font style inside the p tags working. Any hints?

Ideally 

```
[{
    "attributes": {
        "font": "Georgia, serif"
    },
    "insert": "Hi mom"
}]
```

would render 

```
<p><span style="font-family:Georgia, serif">Hi mom</span></p>
```

**Comment by daguej** [comment]
`<font>` is its own [element](
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font), not an
attribute.  It should work just like the other inline styles:

    render.format.inline.font = function($, faces) {
        return $('<font>').attr('face', faces);
    };

Which would render:

    <p><font face="Georgia, serif">Hi mom</font></p>

**Comment by daguej** [comment]
`<font>` is its own [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font), not an attribute.  It should work just like the [other inline styles](https://github.com/casetext/quill-render/blob/v1.0.4/index.js#L20-L30):

```
render.format.inline.font = function($, faces) {
    return $('<font>').attr('face', faces);
};
```

Which would render:

```
<p><font face="Georgia, serif">Hi mom</font></p>
```

---

Just noticed you updated the issue to use CSS instead -- same deal, but with `$('<span>').attr('style', 'font-family:' + faces);` instead.  If you're doing CSS, make sure you sanitize `faces` first.
